{{- if .Values.infrastructure.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.global.certManagerEmail }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
          podTemplate:
            metadata:
              annotations:
                # Ensure the challenge pods use HTTP (not HTTPS)
                traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}