apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timothyw-dev-ingress
  namespace: {{ .Values.namespace }}
  annotations: {}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: timothyw-dev-service
            port:
              number: 80