apiVersion: v1
kind: Service
metadata:
  name: timothyw-dev-service
  namespace: {{ .Values.namespace }}
  labels:
    app: timothyw-dev
spec:
  selector:
    app: timothyw-dev
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP